apiVersion: v1
kind: Namespace
metadata:
  name: chat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librechat
  namespace: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librechat
  template:
    metadata:
      labels:
        app: librechat
    spec:
      containers:
      - name: librechat
        image: ghcr.io/danny-avila/librechat:latest
        env:
        - name: OLLAMA_BASE_URL
          value: http://ollama.ollama.svc.cluster.local:11434
        ports:
        - containerPort: 3080
---
apiVersion: v1
kind: Service
metadata:
  name: librechat
  namespace: chat
spec:
  type: NodePort
  ports:
  - port: 3080
    targetPort: 3080
    nodePort: 31080
  selector:
    app: librechat
