apiVersion: v1
kind: ServiceAccount
metadata:
  name: librechat
  namespace: chat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deny-ollama
  namespace: ollama
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: librechat-deny
  namespace: ollama
subjects:
- kind: ServiceAccount
  name: librechat
  namespace: chat
roleRef:
  kind: Role
  name: deny-ollama
  apiGroup: rbac.authorization.k8s.io
