kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31434
    hostPort: 11434
    protocol: TCP
  - containerPort: 31080
    hostPort: 3080
    protocol: TCP
